
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR x86_64)


set(CMAKE_C_COMPILER gcc)
set(CMAKE_CXX_COMPILER g++)


set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++23 -fPIC")
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fPIC")


if(DEFINED ENV{VCPKG_HOME})
    set(CMAKE_PREFIX_PATH "$ENV{VCPKG_HOME}/installed/x64-linux")
    message(STATUS "Using WSL vcpkg from: $ENV{VCPKG_HOME}")
else()

    set(CMAKE_PREFIX_PATH "/home/$ENV{USER}/.vcpkg/installed/x64-linux")
endif()

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)